[package]
name = "brood"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = "0.11.2"
serde = {version = "1.0.130", default-features = false, features = ["alloc"], optional = true}

[dev-dependencies]
serde_test = "1.0.130"
