[package]
name = "brood"
version = "0.1.0"
edition = "2021"
rust-version = "1.58.0"

[dependencies]
ahash = {version = "0.7.6", default-features = false}
either = {version = "1.6.1", default-features = false}
hashbrown = {version = "0.11.2", features = ["raw"]}
rayon = {version = "1.5.1", optional = true}
serde = {version = "1.0.133", default-features = false, features = ["alloc"], optional = true}

[dev-dependencies]
serde_test = "1.0.133"

[features]
# TODO: Rename this to "rayon" when namespaced dependencies are stabilized in 1.60.0.
parallel = ["rayon", "hashbrown/rayon"]
