[package]
name = "brood"
version = "0.1.0"
edition = "2021"
rust-version = "1.58.0"

[package.metadata.docs.rs]
# To build locally:
# RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --no-deps --open
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[dependencies]
ahash = {version = "0.7.6", default-features = false}
either = {version = "1.6.1", default-features = false}
hashbrown = {version = "0.12.0", features = ["raw"]}
rayon = {version = "1.5.1", optional = true}
serde = {version = "1.0.133", default-features = false, features = ["alloc"], optional = true}

[dev-dependencies]
claim = "0.5.0"
rustversion = "1.0.6"
serde_test = "1.0.133"
trybuild = "1.0.56"

[features]
# TODO: Rename this to "rayon" when namespaced dependencies are stabilized in 1.60.0.
parallel = ["rayon", "hashbrown/rayon"]
