use crate::{
    hlist::define_null,
    registry::Registry,
    system::schedule::{
        claim,
        stages,
        task,
        Stager,
        Stages,
    },
};

define_null!();

pub trait Scheduler<
    'a,
    R,
    Resources,
    I,
    P,
    RI,
    MergeParamtersList,
    ResourcesIndicesLists,
    ResourcesContainmentsLists,
    ResourcesInverseIndicesLists,
    QueryIndicesLists,
    ResourceViewsIndicesLists,
    EntryViewsIndicesLists,
    EntryViewsInverseIndicesLists,
    EntryViewsOppositeIndicesLists,
    EntryViewsOppositeInverseIndicesLists,
    EntryIndicesLists,
> where
    R: Registry,
{
    type Stages: Stages<
        'a,
        R,
        Resources,
        QueryIndicesLists,
        ResourceViewsIndicesLists,
        EntryViewsIndicesLists,
        EntryViewsInverseIndicesLists,
        EntryViewsOppositeIndicesLists,
        EntryViewsOppositeInverseIndicesLists,
        EntryIndicesLists,
    >;

    fn as_stages(&'a mut self) -> Self::Stages;
}

impl<'a, R, Resources>
    Scheduler<
        'a,
        R,
        Resources,
        Null,
        Null,
        Null,
        stages::Null,
        stages::Null,
        stages::Null,
        stages::Null,
        stages::Null,
        stages::Null,
        stages::Null,
        stages::Null,
        stages::Null,
        stages::Null,
        stages::Null,
    > for task::Null
where
    R: Registry,
{
    type Stages = stages::Null;

    #[inline]
    fn as_stages(&'a mut self) -> Self::Stages {
        stages::Null
    }
}

impl<
        'a,
        R,
        Resources,
        T,
        U,
        I,
        IS,
        P,
        PS,
        RI,
        RIS,
        MergeParameters,
        MergeParametersList,
        ResourcesIndicesList,
        ResourcesIndicesLists,
        ResourcesContainmentsList,
        ResourcesContainmentsLists,
        ResourcesInverseIndicesList,
        ResourcesInverseIndicesLists,
        QueryIndicesList,
        QueryIndicesLists,
        ResourceViewsIndicesList,
        ResourceViewsIndicesLists,
        EntryViewsIndicesList,
        EntryViewsIndicesLists,
        EntryViewsInverseIndicesList,
        EntryViewsInverseIndicesLists,
        EntryViewsOppositeIndicesList,
        EntryViewsOppositeIndicesLists,
        EntryViewsOppositeInverseIndicesList,
        EntryViewsOppositeInverseIndicesLists,
        EntryIndicesList,
        EntryIndicesLists,
    >
    Scheduler<
        'a,
        R,
        Resources,
        (I, IS),
        (P, PS),
        (RI, RIS),
        (MergeParameters, MergeParametersList),
        (ResourcesIndicesList, ResourcesIndicesLists),
        (ResourcesContainmentsList, ResourcesContainmentsLists),
        (ResourcesInverseIndicesList, ResourcesInverseIndicesLists),
        (QueryIndicesList, QueryIndicesLists),
        (ResourceViewsIndicesList, ResourceViewsIndicesLists),
        (EntryViewsIndicesList, EntryViewsIndicesLists),
        (EntryViewsInverseIndicesList, EntryViewsInverseIndicesLists),
        (
            EntryViewsOppositeIndicesList,
            EntryViewsOppositeIndicesLists,
        ),
        (
            EntryViewsOppositeInverseIndicesList,
            EntryViewsOppositeInverseIndicesLists,
        ),
        (EntryIndicesList, EntryIndicesLists),
    > for (T, U)
where
    (T, U): Stager<
        'a,
        R,
        Resources,
        claim::Null,
        I,
        P,
        RI,
        MergeParameters,
        claim::Null,
        ResourcesIndicesList,
        ResourcesContainmentsList,
        ResourcesInverseIndicesList,
        QueryIndicesList,
        ResourceViewsIndicesList,
        EntryViewsIndicesList,
        EntryViewsInverseIndicesList,
        EntryViewsOppositeIndicesList,
        EntryViewsOppositeInverseIndicesList,
        EntryIndicesList,
    >,
    <(T, U) as Stager<
        'a,
        R,
        Resources,
        claim::Null,
        I,
        P,
        RI,
        MergeParameters,
        claim::Null,
        ResourcesIndicesList,
        ResourcesContainmentsList,
        ResourcesInverseIndicesList,
        QueryIndicesList,
        ResourceViewsIndicesList,
        EntryViewsIndicesList,
        EntryViewsInverseIndicesList,
        EntryViewsOppositeIndicesList,
        EntryViewsOppositeInverseIndicesList,
        EntryIndicesList,
    >>::Remainder: Scheduler<
        'a,
        R,
        Resources,
        IS,
        PS,
        RIS,
        MergeParametersList,
        ResourcesIndicesLists,
        ResourcesContainmentsLists,
        ResourcesInverseIndicesLists,
        QueryIndicesLists,
        ResourceViewsIndicesLists,
        EntryViewsIndicesLists,
        EntryViewsInverseIndicesLists,
        EntryViewsOppositeIndicesLists,
        EntryViewsOppositeInverseIndicesLists,
        EntryIndicesLists,
    >,
    R: Registry + 'a,
    Resources: 'a,
    I: 'a,
    P: 'a,
    RI: 'a,
    MergeParameters: 'a,
    ResourcesIndicesList: 'a,
    ResourcesContainmentsList: 'a,
    ResourcesInverseIndicesList: 'a,
    QueryIndicesList: 'a,
    ResourceViewsIndicesList: 'a,
    EntryViewsIndicesList: 'a,
    EntryViewsInverseIndicesList: 'a,
    EntryViewsOppositeIndicesList: 'a,
    EntryViewsOppositeInverseIndicesList: 'a,
    EntryIndicesList: 'a,
{
    type Stages = (
        <(T, U) as Stager<
            'a,
            R,
            Resources,
            claim::Null,
            I,
            P,
            RI,
            MergeParameters,
            claim::Null,
            ResourcesIndicesList,
            ResourcesContainmentsList,
            ResourcesInverseIndicesList,
            QueryIndicesList,
            ResourceViewsIndicesList,
            EntryViewsIndicesList,
            EntryViewsInverseIndicesList,
            EntryViewsOppositeIndicesList,
            EntryViewsOppositeInverseIndicesList,
            EntryIndicesList,
        >>::Stage,
        <<(T, U) as Stager<
            'a,
            R,
            Resources,
            claim::Null,
            I,
            P,
            RI,
            MergeParameters,
            claim::Null,
            ResourcesIndicesList,
            ResourcesContainmentsList,
            ResourcesInverseIndicesList,
            QueryIndicesList,
            ResourceViewsIndicesList,
            EntryViewsIndicesList,
            EntryViewsInverseIndicesList,
            EntryViewsOppositeIndicesList,
            EntryViewsOppositeInverseIndicesList,
            EntryIndicesList,
        >>::Remainder as Scheduler<
            'a,
            R,
            Resources,
            IS,
            PS,
            RIS,
            MergeParametersList,
            ResourcesIndicesLists,
            ResourcesContainmentsLists,
            ResourcesInverseIndicesLists,
            QueryIndicesLists,
            ResourceViewsIndicesLists,
            EntryViewsIndicesLists,
            EntryViewsInverseIndicesLists,
            EntryViewsOppositeIndicesLists,
            EntryViewsOppositeInverseIndicesLists,
            EntryIndicesLists,
        >>::Stages,
    );

    #[inline]
    fn as_stages(&'a mut self) -> Self::Stages {
        let (stage, remainder) = self.extract_stage();
        (stage, remainder.as_stages())
    }
}
