name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-hack
    - uses: actions-rs/cargo@v1
      with:
        command: hack
        args: test --feature-powerset --optional-deps

  no_std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: thumbv6m-none-eabi
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-hack
    - uses: actions-rs/cargo@v1
      with:
        command: hack
        args: build --feature-powerset --optional-deps --target thumbv6m-none-eabi

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-hack
    - uses: actions-rs/cargo@v1
      with:
        command: hack
        args: check --feature-powerset --optional-deps

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: miri
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-hack
    - uses: actions-rs/cargo@v1
      with:
        command: hack
        args: miri test --feature-powerset --optional-deps

  valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install valgrind
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-valgrind
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-hack
    - uses: actions-rs/cargo@v1
      with:
        command: hack
        args: valgrind test --feature-powerset --optional-deps
