name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.58.0
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-hack
    - uses: actions-rs/cargo@v1
      with:
        command: hack
        args: test --feature-powerset --optional-deps

  mutants:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.58.0
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-mutants
    - uses: actions-rs/cargo@v1
      with:
        command: mutants
        args: -- --all-targets --all-features

  no_std:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.58.0
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        target: thumbv6m-none-eabi
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-hack
    - uses: actions-rs/cargo@v1
      with:
        command: hack
        args: build --feature-powerset --optional-deps --exclude-features parallel --exclude-features rayon --target thumbv6m-none-eabi

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-hack
    - uses: actions-rs/cargo@v1
      with:
        command: hack
        args: check --feature-powerset --optional-deps

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: clippy
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-hack
    - uses: actions-rs/cargo@v1
      with:
        command: hack
        args: clippy --feature-powerset --optional-deps -- --deny warnings

  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-msrv
    - uses: actions-rs/cargo@v1
      with:
        command: msrv
        args: --verify

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: miri
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-hack
    - uses: actions-rs/cargo@v1
      with:
        command: hack
        args: miri test --feature-powerset --optional-deps
      env:
        MIRIFLAGS: -Zmiri-disable-isolation -Zmiri-ignore-leaks

  valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: wget https://sourceware.org/pub/valgrind/valgrind-3.18.1.tar.bz2
    - run: tar xvf valgrind-3.18.1.tar.bz2
    - run: ./configure
      working-directory: ./valgrind-3.18.1
    - run: make
      working-directory: ./valgrind-3.18.1
    - run: sudo make install
      working-directory: ./valgrind-3.18.1
    - run: sudo apt-get install libc6-dbg:i386
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-valgrind
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-hack
    - uses: actions-rs/cargo@v1
      with:
        command: hack
        args: valgrind test --feature-powerset --optional-deps

  codecov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: llvm-tools-preview
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-llvm-cov
    - uses: actions-rs/cargo@v1
      with:
        command: llvm-cov
        args: --all-features --lcov --output-path lcov.info
    - uses: codecov/codecov-action@v2
      with:
        files: lcov.info
        fail_ci_if_error: true
